COMP003B.Assignment6/Models/ErrorViewModel.cs
namespace COMP003B.Assignment6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

COMP003B.Assignment6/Controllers/HomeController.cs
using COMP003B.Assignment6.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace COMP003B.Assignment6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

COMP003B.Assignment6/Controllers/LifetimeDemoController.cs
using COMP003B.Assignment6.Services;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment6.Controllers
{
    public class LifetimeDemoController : Controller
    {
        
        private readonly MyTransientService _transientService1;
        private readonly MyTransientService _transientService2;
        private readonly MyScopedService _scopedService1;
        private readonly MyScopedService _scopedService2;
        private readonly MySingletonService _singletonService1;
        private readonly MySingletonService _singletonService2;

        public LifetimeDemoController(MyTransientService transientService1,
        MyScopedService scopedService1, MySingletonService singletonService1,
        MyTransientService transientService2,MyScopedService scopedService2,
        MySingletonService singletonService2) 
        {
            _transientService1 = transientService1;
            _transientService2 = transientService2;
            _scopedService1 = scopedService1;
            _scopedService2 = scopedService2;
            _singletonService1 = singletonService1;
            _singletonService2 = singletonService2;
        }

        public IActionResult LifetimeDemo()
        {
            ViewData["TransientId1"] = _transientService1.GetUniqueId();
            ViewData["TransientId2"] = _transientService2.GetUniqueId();
            ViewData["ScopedId1"] = _scopedService1.GetUniqueId();
            ViewData["ScopedId2"] = _scopedService2.GetUniqueId();
            ViewData["SingletonId1"] = _singletonService1.GetUniqueId();
            ViewData["SingletonId2"] = _singletonService2.GetUniqueId();

            return View();
        }
    }
}

COMP003B.Assignment6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

COMP003B.Assignment6/Views/LifetimeDemo/LifetimeDemo.cshtml
@{
    ViewData["Title"] = "Lifetime Demo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Refresh/Reload this page and observe the difference</h2>

<h3>Transient</h3>
<p>
    Transient: A new instance of the service is  created every time it is requested.
    Therefore, the UniqueId property of the TransientService will be different each time you
    visit the Transient action method.
</p>
<p stlye="font-weight:bold">Transient Service ID 1: @ViewData["TransientId1"]</p>
<p stlye="font-weight:bold">Transient Service ID 2: @ViewData["TransientId2"]</p>

<h3>Scoped</h3>
<p>
    Scoped: The service instance is shared within the scope of an HTTP request. When you
    visit the Scoped action method, the UniqueId property of the ScopedService will be the
    same for each visit within the same request but different between requests.
</p>
<p style="font-weight:bold">Scoped Service ID 1: @ViewData["ScopedId1"]</p>
<p style="font-weight:bold">Scoped Service ID 2: @ViewData["ScopedId2"]</p>

<h3>Singleton</h3>
<p>
    Singleton: Only one instance of the service is created, and it is shared throughout
    the entire application. The UniqueId property of the SingletonService will remain the
    same for all visits to the Singleton action method.
</p>
<p style="font-weight:bold">Singleton Service ID 1: @ViewData["SingletonId1"]</p>
<p style="font-weight:bold">Singleton Service ID 2: @ViewData["SingletonId2"]</p>

COMP003B.Assignment6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COMP003B.Assignment6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.Assignment6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COMP003B.Assignment6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LifetimeDemo" asp-action="LifetimeDemo">LifeTime Demo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - COMP003B.Assignment6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>